sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - clang-3.8
      - libclang-common-3.8-dev
      - ninja-build

script: ./build/travis_build.sh
